### ISSUE TITLE
SSL should be enabled by default

### ISSUE THREAD

**Issue by mijaros** [jcechace/RbShift#11]
https://github.com/jcechace/RbShift/blob/c98f92495f10d5d7c32b21c71ac2ded0167ccaa4/lib/rb_shift/client.rb#L28

**Comment by jcechace** [comment]
@mijaros  skipped the PR for this since it's a very minor change.

Change based on https://github.com/rest-client/rest-client/blob/master/lib/restclient/request.rb#L112

seems to work fine.
