### ISSUE TITLE
Project listing/access should be lazy

### ISSUE THREAD

**Issue by jcechace** [jcechace/RbShift#7]
When accessing a list of project there is a REST call performed for each of the project.  This initial access should be made lazy.

**Comment by jcechace** [comment]
@mijaros should be done, right?

**Comment by mijaros** [comment]
Yes, by referenced commit  c98f92495f10d5d7c32b21c71ac2ded0167ccaa4 which is alredy merged into master.

**Comment by jcechace** [comment]
Fixed by c98f924
