### ISSUE TITLE
Logging support in RbShift

### ISSUE THREAD

**Issue by jcechace** [jcechace/RbShift#9]
Logging is live, logging is life!

**Comment by jcechace** [comment]
@mijaros do we close this or leave it open? Support is there,, however it probably isn't used at all the places it should be... yet

**Comment by mijaros** [comment]
I whould leave this open until all necessary actions are properly logged.

**Comment by jcechace** [comment]
I have an idea....

**Comment by jcechace** [comment]
Resolved in 2e371f6
